### PR TITLE
[BUGFIX] better handling external type page of typolink

### LINKED ISSUE #234: lib.parseFunc_links handles incorrectly external link doktype
instead of external url returns json output.

Steps to reproduce

1. Create page with external link
2. in another page in RTE field put link to page created in step 1
3. instead in generated link have link to external site we have full typolink output

### PR DESCRIPTION
**Pull request by twoldanski**
- cs cleanup
- minor optimizations
- resolves #234

### CODE REVIEW

File: Classes/Hooks/TypolinkHook.php [hunk 1]
```diff
@@ -13,23 +13,14 @@
 
 namespace FriendsOfTYPO3\Headless\Hooks;
 
+use TYPO3\CMS\Core\Configuration\Features;
+use TYPO3\CMS\Core\Utility\GeneralUtility;
 use TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer;
 use TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController;
 
-/***
```
Comment (lukaszuznanski) [inline Classes/Hooks/TypolinkHook.php:19]: we should add license as in other files

**Review by lukaszuznanski — CHANGES_REQUESTED** [review]

**Review by lukaszuznanski — APPROVED** [review]
